// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmXCzld98zzHruueSGCS_KjLjvaDUf304',
    appId: '1:250646997957:web:4ca7d393b5b1edd391f9ac',
    messagingSenderId: '250646997957',
    projectId: 'omlaademoapp',
    authDomain: 'omlaademoapp.firebaseapp.com',
    storageBucket: 'omlaademoapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8lMLdzY0NJRH27sKVdA11P248regdE2g',
    appId: '1:250646997957:android:74e32cccae5f953e91f9ac',
    messagingSenderId: '250646997957',
    projectId: 'omlaademoapp',
    storageBucket: 'omlaademoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwdAEUWSOvEmKl8L7wq4V7p9hIECOKABA',
    appId: '1:250646997957:ios:29caa89126fe3b3391f9ac',
    messagingSenderId: '250646997957',
    projectId: 'omlaademoapp',
    storageBucket: 'omlaademoapp.appspot.com',
    iosBundleId: 'com.example.omlaDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwdAEUWSOvEmKl8L7wq4V7p9hIECOKABA',
    appId: '1:250646997957:ios:8824aff5c3fbe5e991f9ac',
    messagingSenderId: '250646997957',
    projectId: 'omlaademoapp',
    storageBucket: 'omlaademoapp.appspot.com',
    iosBundleId: 'com.example.omlaDemoApp.RunnerTests',
  );
}
